apiVersion: apps/v1
kind: Deployment
metadata:
  name: hostname-viewer
  namespace: demo
spec:
  replicas: 6
  selector:
    matchLabels:
      app: hostname-viewer
  template:
    metadata:
      labels:
        app: hostname-viewer
    spec:
      containers:
        - name: hostname-viewer
          image: soominchae/hostname-viewer:latest
          ports:
            - containerPort: 5000
